### ISSUE TITLE
A model containing an empty businessKnowledgeModel element will throw a NullPointerException when parsing

### ISSUE THREAD

**Issue by EdCurran** [camunda/dmn-scala#6]
A model containing an empty "businessKnowledgeModel" element (as generated by camunda modeler) will fail to parse with the following exception, seen in dmn-engine 1.3.1:

`Exception in thread "main" java.lang.NullPointerException
	at org.camunda.dmn.parser.DmnParser.parseBusinessKnowledgeModel(DmnParser.scala:158)
	at org.camunda.dmn.parser.DmnParser.$anonfun$parseDecision$7(DmnParser.scala:116)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at org.camunda.dmn.parser.DmnParser.$anonfun$parseDecision$6(DmnParser.scala:116)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.immutable.List.map(List.scala:298)
	at org.camunda.dmn.parser.DmnParser.parseDecision(DmnParser.scala:115)
	at org.camunda.dmn.parser.DmnParser.$anonfun$parseModel$3(DmnParser.scala:91)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at org.camunda.dmn.parser.DmnParser.$anonfun$parseModel$2(DmnParser.scala:91)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.immutable.List.map(List.scala:298)
	at org.camunda.dmn.parser.DmnParser.parseModel(DmnParser.scala:89)
	at org.camunda.dmn.parser.DmnParser.parse(DmnParser.scala:74)
	at org.camunda.dmn.DmnEngine.parse(DmnEngine.scala:134)
	at model.dmn.ModelEvaluatorDmnScala$.getDecisionFunctions(ModelEvaluatorDmnScala.scala:79)
	at decisionservice.CmdLineClient$.$anonfun$loadScoreFunctions$4(CmdLineClient.scala:179)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:75)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at decisionservice.CmdLineClient$.loadScoreFunctions(CmdLineClient.scala:179)
	at decisionservice.CmdLineClient$.setup(CmdLineClient.scala:61)
	at decisionservice.CmdLineClient$.main(CmdLineClient.scala:30)
	at decisionservice.CmdLineClient.main(CmdLineClient.scala)`

Here's an example dmn model that will cause this, as generated by camunda modeler (I included some comments)

```xml

<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/DMN/20151101/dmn.xsd" xmlns:biodi="http://bpmn.io/schema/dmn/biodi/1.0" id="Definitions_0cum8ey" name="DRD" namespace="http://camunda.org/schema/1.0/dmn" exporter="Camunda Modeler" exporterVersion="3.1.2">
  <decision id="decision_bkm_parse_test" name="expression test">
    <extensionElements>
      <biodi:bounds x="521" y="81" width="180" height="80" />
      <biodi:edge source="BusinessKnowledgeModel_1en940y">
        <biodi:waypoints x="291" y="118" />
        <biodi:waypoints x="521" y="120" />
      </biodi:edge>
    </extensionElements>
    <variable id="InformationItem_1mbj8gg" name="expressionOutput" typeRef="string" />
    <knowledgeRequirement>
      <requiredKnowledge href="#BusinessKnowledgeModel_1en940y" />
    </knowledgeRequirement>
    <literalExpression id="LiteralExpression_0ycsm8o" expressionLanguage="feel">
      <text>"parsed correctly"</text>
    </literalExpression>
  </decision>
  <businessKnowledgeModel id="BusinessKnowledgeModel_1en940y" name="my buisness model">
    <extensionElements>
      <biodi:bounds x="156" y="94" width="135" height="46" />
    </extensionElements>

    <!--not having this breaks it-->
    <!--<encapsulatedLogic>-->
    <!--</encapsulatedLogic>-->

    <!--can even do this-->
    <!--<nothing/>-->
  </businessKnowledgeModel>
</definitions>


```

It's expecting an "encapsulatedLogic" element within the "businessKnowledgeModel" element. Including that will fix the problem. Actually including any nonsense element will allow the model to parse. Having or not having an "extensionElements" element has no effect.

Obviously camunda modeler doesn't allow any functionality within BKM's but would be nice to include in diagrams as a placeholder. 

I'm not sure if this incompatibility should be fixed on dmn-scala end or modeler end. In this case seems that dmn-scala should at least be able to parse and give a reasonable error rather than NullPointerException

**Comment by saig0** [comment]
Thank's for raising this up!

I'm not sure about the expected behavior. Since the BKM is referred by a decision, I would return a parsing failure to indicate that the `encapsulatedLogic` is missing. Ignoring may lead to other problems at runtime that are less obvious.

Is this ok for you?

**Comment by EdCurran** [comment]
Yeah does make sense to me. Is a bit of a shame as I wanted to be able to build models with the modeler where a BKM is referred to by a decision basically as a form of self documentation for now. 

I've used the custom function provider to inject PMML models (using JPMML evaluator) as functions to make them available in the DMN model. I wanted to include a BKM to represent a PMML model that is used by a decision element.  Ideally this integration would be a lot nicer but I figured I could do something simple like give the BKM the same name as a PMML model prefixed with PMML_ and that would do for now and still be constructable with the modeler. 

Does this mean if an empty BKM isn't referred to by a decision then it will parse? I could just include some unconnected BKM's to fulfil the same purpose. More accurate in a way as the PMML is available to the whole model as a function in reality.

**Comment by saig0** [comment]
> Does this mean if an empty BKM isn't referred to by a decision then it will parse?

Correct.

> I've used the custom function provider to inject PMML models

Interesting use case! Feel free to open a new issue if you want to discuss how the integration of PMML could be improved (e.g. writing PMML in the DMN, importing PMML files).

**Comment by saig0** [comment]
I fixed the issue in a way that BKMs without encapsulated logic are ignored.
